#!/usr/bin/env ruby
# encoding: utf-8

OUTPUT_DIR = File.expand_path("~/projects/rezepte/src")
EDITOR = ENV['EDITOR'] || 'vim'
EXTENSION=".md"
HEADER = <<EOF
# %s

EOF
SUMMARY = <<EOF
- [%s](./%s.md)
EOF

if ARGV.size == 0
  $stderr.puts "usage: #{File.basename($0)} title"
  exit 1
end

def slugify(args)
  args.map { |arg|
    arg.downcase.gsub(/[^a-z0-9]/, '-')
  }.join('-').gsub(/--+/, '-').gsub(/-$/, '')
end

filename = slugify(ARGV)
title = ARGV.join(' ')
file = File.join(OUTPUT_DIR, "#{filename}#{EXTENSION}")
summary_file = File.join(OUTPUT_DIR, "SUMMARY.md")

puts "new recipe: #{title}"
puts "file: #{filename}"
File.open(file, "w"){|f| f.write(HEADER % [title]) }
File.open(summary_file, "a") {|f| f.write(SUMMARY % [title, filename])}
exec EDITOR, '+', file
